---
- name: play configures next gen lab routers
  hosts: nglrouters
  timeout: 40
  tasks:
  - name: configure washington dc router
    ansible.builtin.include_tasks:
      file: tasks/washdc.yaml
    when: inventory_hostname == 'washdc'

  - name: configure michigan router
    ansible.builtin.include_tasks:
      file: tasks/michigan.yaml
    when: inventory_hostname == "michigan"

  - name: configure virginia router
    ansible.builtin.include_tasks:
      file: tasks/virginia.yaml
    when: inventory_hostname == "virginia"
