#display michigan 
- name: diplay router name
  ansible.builtin.debug:
    msg: "Configuring {{ inventory_hostname }}"

#change hostname of michigan router
- name: task changes hostname 
  cisco.ios.ios_config:
   lines:
       - hostname {{ inventory_hostname }}
   diff_against: startup
   save_when: modified

#configure ipv4 and ipv6 addresses on interfaces
#interface gig0/1
- name: remove ip address on gig0/1
  cisco.ios.ios_config:
   parents: interface gigabitethernet 0/1
   lines:
    - no ip address
    - no ipv6 address
    - shutdown
   diff_against: startup
   save_when: modified

#interface gig03 
- name: configure ip addresses on interfaces g0/3
  cisco.ios.ios_config:
   parents: interface gigabitethernet 0/3
   lines:
      - ip address 23.205.1.34 255.255.255.252
      - no shutdown
      - ipv6 address 329E:A2DC:4:5::3:1/64
      - description "connected to washdc"
   diff_against: startup
   save_when: modified

