#change hostname
- name: task changes hostname for R2
  cisco.ios.ios_hostname:
   config:
    hostname: michigan
   state: merged
  when: inventory_hostname == "michigan"
#configure ipv4 and ipv6 addresses on interfaces
- name: configure ip addresses on interfaces g0/3
  cisco.ios.ios_l3_interfaces:
    config:
      - name: GigabitEthernet0/1
        ipv4:
          - address: 23.205.1.34/30
        ipv6:
          - address: 329e:a2dc:4:5::3:1/64
            #    state: merged
  when: inventory_hostname == "michigan"

